In [15]:
import pandas as pd
import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [3]:
drybean = pd.read_excel("/content/Dry_Bean_Dataset.xlsx")

In [6]:
drybean.head()

    Area  Perimeter  MajorAxisLength  ...  ShapeFactor3  ShapeFactor4  Class
0  28395    610.291       208.178117  ...      0.834222      0.998724  SEKER
1  28734    638.018       200.524796  ...      0.909851      0.998430  SEKER
2  29380    624.110       212.826130  ...      0.825871      0.999066  SEKER
3  30008    645.884       210.557999  ...      0.861794      0.994199  SEKER
4  30140    620.134       201.847882  ...      0.941900      0.999166  SEKER

[5 rows x 17 columns]

In [7]:
X = drybean.iloc[:,0:4]
X

        Area  Perimeter  MajorAxisLength  MinorAxisLength
0      28395    610.291       208.178117       173.888747
1      28734    638.018       200.524796       182.734419
2      29380    624.110       212.826130       175.931143
3      30008    645.884       210.557999       182.516516
4      30140    620.134       201.847882       190.279279
...      ...        ...              ...              ...
13606  42097    759.696       288.721612       185.944705
13607  42101    757.499       281.576392       190.713136
13608  42139    759.321       281.539928       191.187979
13609  42147    763.779       283.382636       190.275731
13610  42159    772.237       295.142741       182.204716

[13611 rows x 4 columns]

In [8]:
y = drybean.select_dtypes(include=[object])
y.head()

   Class
0  SEKER
1  SEKER
2  SEKER
3  SEKER
4  SEKER

In [9]:
X.head()

    Area  Perimeter  MajorAxisLength  MinorAxisLength
0  28395    610.291       208.178117       173.888747
1  28734    638.018       200.524796       182.734419
2  29380    624.110       212.826130       175.931143
3  30008    645.884       210.557999       182.516516
4  30140    620.134       201.847882       190.279279

In [10]:
y.Class.unique()

array(['SEKER', 'BARBUNYA', 'BOMBAY', 'CALI', 'HOROZ', 'SIRA', 'DERMASON'],
      dtype=object)

In [11]:
le = preprocessing.LabelEncoder()
y = y.apply(le.fit_transform)
y.head()

   Class
0      5
1      5
2      5
3      5
4      5

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [13]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)
mlp.fit(X_train, y_train.values.ravel())

MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)

In [17]:
predictions = mlp.predict(X_test)
predictions

array([6, 3, 3, ..., 5, 6, 0])

In [24]:
print("Confusion Matrix:\n")
confusion_matrix(y_test,predictions)

Confusion Matrix:

array([[222,   0,  21,   0,   4,   2,   8],
       [  0,  93,   0,   0,   0,   0,   0],
       [ 10,   0, 311,   0,   8,   0,   4],
       [  0,   0,   0, 664,   3,  10,  47],
       [  4,   0,   4,   2, 361,   0,  14],
       [  3,   0,   0,   9,   0, 398,  23],
       [  1,   0,   0,  49,   9,   6, 433]])

In [25]:
print("Classification Report:\n")
print(classification_report(y_test,predictions))

Classification Report:

              precision    recall  f1-score   support

           0       0.93      0.86      0.89       257
           1       1.00      1.00      1.00        93
           2       0.93      0.93      0.93       333
           3       0.92      0.92      0.92       724
           4       0.94      0.94      0.94       385
           5       0.96      0.92      0.94       433
           6       0.82      0.87      0.84       498

    accuracy                           0.91      2723
   macro avg       0.93      0.92      0.92      2723
weighted avg       0.91      0.91      0.91      2723